packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  - 'examples/*'
  - 'playground'
  - 'docs'
  # exclude packages that are inside test directories
  - '!**/test/**'
